### PR TITLE
Fix build on FreeBSD/powerpc64le

### PR DESCRIPTION
**Pull request by pkubaj**
Use elf_aux_info() instead of getauxval() on FreeBSD.

### CODE REVIEW

**Comment by rschu1ze** [comment]
@pkubaj 

1. Just wondering, is this fix already in upstream zlib-ng? If yes, we should rather merge upstream zlib-ng into ClickHouse's zlib-ng fork. If no, do you plan to contribute it back to upstream zlib-ng (see pt. 5 [here](https://clickhouse.com/docs/en/development/contrib#adding-third-party-libraries))?

2. You would also need to update the zlib-ng submodule in the [ClickHouse repository](https://github.com/ClickHouse/ClickHouse). Does a PR already exist? (Such a PR can be created without this PR being merged).

**Comment by pkubaj** [comment]
I sent the PR upstream at https://github.com/zlib-ng/zlib-ng/pull/1340, but unfortunately mixed branches, will fix later.

**Comment by rschu1ze** [comment]
Thanks.

Mixed branches? Guess you mean your PR pulls in a ton of unrelated stuff. The ClickHouse repository references the `clickhouse-2.0.x` branch of this repository.

**Comment by rschu1ze** [comment]
Question 1: we should drop all commits except [this one](https://github.com/ClickHouse/zlib-ng/pull/14/commits/6f9482caee90f87bbb20e2c70d9793f5db5c866d) from this PR, either by force-pushing or by closing this PR and opening a new one. Also see my [previous comment](https://github.com/ClickHouse/zlib-ng/pull/14#issuecomment-1239392236).

Question 2: looking at file `contrib/zlib-ng-cmake/CMakeLists.txt` in ClickHouse's repository, I wonder how file `detect-intrinsics.cmake` is called/reached from ClickHouse's build. ClickHouse pursues a "bundling" approach where 3rs party libs are not build using their native build script but using a ClickHouse-specific, re-implemented CMake build script. But maybe I miss something here.

**Comment by pkubaj** [comment]
Sorry for the confusion. I accidentally used the same branch for upstreaming the zlib-ng change as here and hence the conflicts. Unfortunately Github doesn't allow changing the source branch, so once it's upstreamed, I'll properly revert upstream's commits from my branch and put your commits so that the repo history will match.

**Comment by rschu1ze** [comment]
I suppose reverting the upstream commits and merging this PR will create 482 + 481 = 963 commits which is exactly 962 too many, i.e. clutters the history 😉 Consider abandoning this PR and opening a new one with a single fix.

Besides that, I still wonder how the fix is relevant for ClickHouse's own "bundled" CMake build description for zlib (--> Question 2 above)

**Comment by pkubaj** [comment]
The upstream fixes are only partially relevant to Clickhouse, but I was asked to upstream my change, hence I'm doing it. Closing this PR for now, until it lands to upstream.

**Pull request closed without merging**
